### ISSUE TITLE
Class 'HTMLPurifier_AttrDef_HTML_Bool2' not found

### ISSUE THREAD

**Issue by TymeOfNight** [xemlock/htmlpurifier-html5#27]
I hope you are doing well. :)

I'm working with HTML Purifier 4.10.0 and HTML5 Plugin version 0.1.8.  Maybe I set something up wrong, but I'm getting a `Class 'HTMLPurifier_AttrDef_HTML_Bool2' not found` error on line 15 of `\library\HTMLPurifier\HTML5Definition.php`.  The error is thrown during the purifying process.  My calling code looks like this:

        $htmlPurifierPath = 'resources/html-purifier/htmlpurifier-4.10.0/library/HTMLPurifier.auto.php';
        $html5PluginRoot = 'resources/html-purifier/htmlpurifier-html5-0.1.8/library/HTMLPurifier';
        $html5PluginConfig = "$html5PluginRoot/HTML5Config.php";
        $html5PluginDefinition = "$html5PluginRoot/HTML5Definition.php";
        
        if (!file_exists($htmlPurifierPath)) {
            throw new Exception("HTML Purifier not found.", 500);
        }
        
        if (file_exists($html5PluginConfig)) {
            $html5 = true;
        }

        require_once $htmlPurifierPath;
        if ($html5) {
            require_once $html5PluginConfig;
            require_once $html5PluginDefinition;
        }
        
        $pdo = connMySql();
        $config = "";
        
        if ($html5) {
            $config = HTMLPurifier_HTML5Config::createDefault();
        } else {
            $config = HTMLPurifier_Config::createDefault();
        }
        
        $purifier = new HTMLPurifier($config);
        
        $html = $purifier->purify($_POST['html']);

The code specified as the source of the error looks like the following:
`// use fixed implementation of Boolean attributes, instead of a buggy`
`// one provided with 4.6.0`
`$def->manager->attrTypes->set('Bool', new HTMLPurifier_AttrDef_HTML_Bool2());`

I noticed in the comment preceding line 15, you were redefining a buggy boolean implementation defined in HTML Purifier version 4.6, which released in 2013.  What would happen if I commented this line out?

Thanks for your time. :)

**Comment by xemlock** [comment]
This library relies on composer autoloader in order to work correctly. So you need to add something like

```php
<?php
require '/path/to/vendor/autoload.php';
```

at the beginning of your application entrypoint file.

Without this none of the classes provided by this library will be loaded.

Is there any particular reason you're not using Composer to manage dependencies?
