### ISSUE TITLE
Add module toggles

### ISSUE THREAD

**Issue by xemlock** [xemlock/htmlpurifier-html5#32]
Currently toggling modules is not granular enough - there is only one switch (`HTML.Trusted`) which enables all unsafe modules. And there is no way of enabling `Forms` module without also enabling `Scripting`. You can do something like the following, but it's not convenient and seems like a dirty override:

```php
$config = new HTMLPurifier_HTML5Config::create([
    'HTML.Trusted' => true,
    'HTML.ForbiddenElements' => ['script', 'noscript'],
]);
```

Related to ezyang/htmlpurifier#213.

**Comment by bytestream** [comment]
How do you envisage this working? I'll submit a PR.

**Comment by bytestream** [comment]
@xemlock ping

**Comment by bytestream** [comment]
It's cumbersome but you can do this using `HTML.AllowedModules`. List all the modules you want to allow and any not listed will be removed.

**Comment by xemlock** [comment]
Closing, as `%HTML.Forms` config flag is sufficient for now.
