### ISSUE TITLE
dir="auto" used to be removed in v0.1.8 but is not in v0.1.10

### ISSUE THREAD

**Issue by howardcox** [xemlock/htmlpurifier-html5#36]
Hi,

We've noticed that dir="auto" is no longer removed in v0.1.10.

Was that a deliberate decision? It's not mentioned in the release notes...

It's not a problem for us, but may be for others.

**Comment by xemlock** [comment]
Hi @howardcox,
`dir="auto"` is a valid attribute as defined in [HTML5 spec](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute). Versions prior to 0.1.9 were using HTMLPurifier's built-in [Bdo implementation](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Bdo.php#L40), which follows [XHTML 1.1 spec](https://www.w3.org/TR/xhtml-modularization/abstract_modules.html#s_bdomodule) and allows only `ltr` and `rtl` values. Version 0.1.9 introduced a proper, HTML5-compliant implementation, which allows all three values.

But you're right - the information about this should (and will) be added to 0.1.9 release notes.

**Comment by howardcox** [comment]
Thanks
