### ISSUE TITLE
ezyang comments

### ISSUE THREAD

**Issue by bytestream** [xemlock/htmlpurifier-html5#37]
I'm looking at switching to this from `ezyang/htmlpurifier` due to growing need for HTML5 support.

Several years ago, `lukusw` tried to add HTML5 support to htmlpurifier for Drupal but I think the idea dropped priority and was never implemented. `ezyang` made some comments on `lukusw`'s attempt which is probably what slowed the whole thing down: https://www.drupal.org/project/htmlpurifier/issues/1321490#comment-9509073

I've been comparing `lukusw` and your code based on `ezyang` comments:
* https://github.com/lukusw/php-htmlpurfier-html5/blob/master/htmlpurifier_html5.php#L40
* https://github.com/xemlock/htmlpurifier-html5/blob/e843e771f778618137f7e3fefbe2015621056c47/library/HTMLPurifier/HTMLModule/HTML5/Text.php#L23

With this in mind, I'm hoping you can answer the below questions:

> All of the HTML5 content needs to be gated, so it is only available when a user specifies an HTML5 doctype. You could try to put all of the HTML5 definitions in a new HTMLModule.

✔️  looks good

> section/nav/aside/article are not Block content but Sectioning content. Flow should be redefined to include Sectioning (similar to how HTMLPurifier/HTMLModule/Text.php does Flow)

❌ Doesn't look to have changed? 

> header and footer need to exclude header/footer/main descendants; see the 'excludes' attribute; also an example in Text.php (pre)

❌ Doesn't look to have changed? 

> Ditto with address, use the same technique

❌ Doesn't look to have changed? 

> hgroup got removed from the HTML5 spec, so doesn't belong here.

✔️ seems fine to keep it

> The figure specification doesn't look right; I think you need an asterisk after the Flow. A plain spec 'Flow' is special-cased. I suspect your specifications also exclude plain text.

❔ not sure if you've done this?

> figcaption is not Inline, give it false instead.

✔️ seems fine

> I'm a little worried about video tag, but the definition you've given is probably OK. I'm not sure if it should be allowed by default. Definitely autoplay should not be allowed. The contents has the same problem as figure.

✔️ allows autoplay, but otherwise seems ok

> We should already have the inline elements; are the existing definitions buggy?

✔️  not sure that this is relevant... Existing definitions are gated to XHTML 1.1, so would need gated definition for html5 spec (http://htmlpurifier.org/phorum/read.php?3,8291,8514#msg-8514)

> For ins/del datetime, ideally we would apply the HTML5 parse a date or time string and validate it, see http://www.w3.org/TR/html5/infrastructure.html#parse-a-date-or-time-string

✔️  seems fine

> iframe allowfullscreen isn't an HTML5 attribute. And it shouldn't be allowed by default anyway, should be gated by Tricky at least.

❌ Not gated by tricky?

**Comment by xemlock** [comment]
Hi @bytestream,
At the moment the points you've marked with ❌ are indeed not yet done. But they're definitely on my to-do list.

As for the `<figure>` element, it has its [own definition](https://github.com/xemlock/htmlpurifier-html5/blob/master/library/HTMLPurifier/ChildDef/HTML5/Figure.php) which follows the intricacies of HTML5 spec, available since 0.1.9.

**Comment by bytestream** [comment]
Would you like some PR's?

1. #38 should just be a `if ($config->get())`  similar to https://github.com/ezyang/htmlpurifier/blob/b81690c17eae5dbea7557d1f359af8dd17e9beef/library/HTMLPurifier/AttrTransform/SafeParam.php#L53
2. #39 and #40 should be similar to https://github.com/ezyang/htmlpurifier/blob/b81690c17eae5dbea7557d1f359af8dd17e9beef/library/HTMLPurifier/HTMLModule/Text.php#L60

It's only the `Sectioning` for `section/nav/aside/article` I'm not too clear on, think he might be referring to https://github.com/ezyang/htmlpurifier/blob/b81690c17eae5dbea7557d1f359af8dd17e9beef/library/HTMLPurifier/HTMLModule/Text.php#L25 but I'm not sure...

**Comment by xemlock** [comment]
#38 needs extending config schema with definition of new settings, otherwise an error will be thrown.

#39 and #40 should use [HTMLPurifier_ChildDef_HTML5](https://github.com/xemlock/htmlpurifier-html5/blob/master/library/HTMLPurifier/ChildDef/HTML5.php#L3) as a base, because the original htmlpurifier's `exclude` functionality is not very useful - it removes direct children only, and we need to remove all unwanted descendants from the subtree.

If you're not in a hurry I can look into it during this weekend.

_Edit:_ I forgot to add that PRs are welcome 🙂

**Comment by bytestream** [comment]
I can wait till the weekend :)

**Comment by xemlock** [comment]
@bytestream I need a few more days, because all these changes require a little bit more work than expected 😅

**Comment by xemlock** [comment]
@bytestream All requested changes have just been released as [v0.1.11](https://github.com/xemlock/htmlpurifier-html5/releases/tag/v0.1.11).

**Comment by bytestream** [comment]
You're awesome bru 🎉 much appreciated.
