### ISSUE TITLE
Add config setting for allowfullscreen iframe attribute

### ISSUE THREAD

**Issue by xemlock** [xemlock/htmlpurifier-html5#38]
Related to #37.

Need something similar to [`HTML.FlashAllowFullScreen`](http://htmlpurifier.org/live/configdoc/plain.html#HTML.FlashAllowFullScreen).

**Comment by bytestream** [comment]
Ref: https://fullscreen.spec.whatwg.org/#security-and-privacy-considerations

**Comment by xemlock** [comment]
@bytestream It turns out the additional config option is actually not needed. Iframe is defined in an  [`Iframe` module](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Iframe.php), which is marked as unsafe - it won't be enabled unless `HTML.Trusted` is explicitly set to `true`.

The `HTML.FlashAllowFullScreen` setting is used in [`SafeObject` module](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/SafeObject.php), because the module defines `<object>` tags in safe mode - and only allows carefully filtered subset of params. Unsafe [`Object` module](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Object.php) has no such restrictions.

So, the only change required is to define `HTML5_Iframe` module which inherits from `Iframe` module, and defines `allowfullscreen` attribute.

**Comment by xemlock** [comment]
Ok, apparently I was wrong 😅. Iframe can be included not only by setting `HTML.Trusted` to `true`, but also by [`HTML.SafeIframe`](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/HTMLModule/Iframe.php#L28). In such case the switch (e.g. `HTML.IframeAllowFullscreen`) is required.
