### ISSUE TITLE
Border-radius getting removed

### ISSUE THREAD

**Issue by Dimrak** [xemlock/htmlpurifier-html5#58]
Hi,

I am using a combination of wkhtmltopdf and htmlpurifier-html5 to generate pdf's.

The problem that I am facing at the moment is that the inline style border-radius gets removed after passing the purify() function.

Any thoughts on why it could be doing this?

Thanks.

**Comment by xemlock** [comment]
Hi @Dimrak,
Looks like [HTMLPurifier](https://github.com/ezyang/htmlpurifier) doesn't support `border-radius`. When I tried explicitly enabling `border-radius` property with:

```php
$config->set('CSS.AllowedProperties', 'border-radius');
```

I got the following:

```
Warning: Style attribute 'border-radius' is not supported (for information on implementing this, see the support forums)  in vendor/ezyang/htmlpurifier/library/HTMLPurifier/CSSDefinition.php on line 518
```

You need to report the missing support for `border-radius` at the [HTMLPurifier repo](https://github.com/ezyang/htmlpurifier/issues).

**Comment by xemlock** [comment]
Hi again @Dimrak,
Just letting you know that I was able to make `border-radius` work by doing:

```php
$config->set('CSS.Proprietary', true);
```

I guess you can close ezyang/htmlpurifier#259 🙂

**Comment by Dimrak** [comment]
Hi @xemlock 

Thanks it works :)
