### ISSUE TITLE
HTML.Forms not working?

### ISSUE THREAD

**Issue by etnyx-efun** [xemlock/htmlpurifier-html5#61]
Hello I want to pass HTML form through purify process, this should by possible in vanilla htmlpurifier since 4.13.0 by "HTML.Forms" but it doesn't seems to work in this html5 extend. Example:

```php
<?php
require 'vendor/autoload.php';

$config = HTMLPurifier_HTML5Config::createDefault();

$config->set('HTML.Trusted', FALSE);
$config->set('HTML.Forms', TRUE);

$purifier = new HTMLPurifier($config);

$dirty_html5 = '<form mnethod="post" action="#"><input></form>';
$clean_html5 = $purifier->purify($dirty_html5);
var_dump(htmlspecialchars($clean_html5));
----------------------
string(0) ""
```

from composer.lock:
```
"name": "ezyang/htmlpurifier",
"version": "v4.13.0",

"name": "xemlock/htmlpurifier-html5",
"version": "v0.1.11",
```

In case of vanilla "ezyang/htmlpurifier:v4.13.0:
```php
<?php

require 'vendor/autoload.php';

$config = HTMLPurifier_Config::createDefault();

$config->set('HTML.Trusted', FALSE);
$config->set('HTML.Forms', TRUE);

$purifier = new HTMLPurifier($config);

$dirty_html5 = '<form mnethod="post" action="#"><input></form>';
$clean_html5 = $purifier->purify($dirty_html5);
var_dump(htmlspecialchars($clean_html5));
--------------------------
string(61) "<form action="#"><input /></form>" 
```

Not sure what's wrong there?

**Comment by xemlock** [comment]
Hi,
`HTML.Forms` config directive will be supported in the upcoming 0.1.12 version. Until it lands you can either use `dev-master` version, or enable forms module with `HTML.Trusted` (please remember to disable script elements!).

**Comment by etnyx-efun** [comment]
Thanks for your fast response, I get it know straight, html5 extension overloading HTML.Forms setup method (https://github.com/xemlock/htmlpurifier-html5/blob/v0.1.11/library/HTMLPurifier/HTMLModule/HTML5/Forms.php) that's why it doesn't work in 0.1.11.

So 
```
	$config->set('HTML.Trusted', TRUE);
	$config->set('HTML.ForbiddenElements', ['script', 'noscript']);
```
should solved it for now or is there something else allowed by HTML.Trusted to disable by design?

**Comment by xemlock** [comment]
You can (should) also disable `iframe` and `object` elements. Better safe than sorry 🙂.

**Comment by etnyx-efun** [comment]
Yes, you are right better safe than sorry. This was bare-bone example, I have iframe filtered by src for some "trusted" source later in config, but object I didn't filtering.

Again thanks for your response, question was solved, closing...
