### ISSUE TITLE
Allow link element

### ISSUE THREAD

**Issue by bytestream** [xemlock/htmlpurifier-html5#62]
Similar to `<script>` it would be good to allow `<link>` if the `href` is whitelisted

I can send a PR if you'll accept it

**Comment by xemlock** [comment]
Hi @bytestream, long time no hear 🙂

Yes, that's a good idea. According to https://html.spec.whatwg.org/multipage/links.html#body-ok, only link `type` attribute values allowed in `<body>` should be supported (as HTML Purifier is designed to work on `body` contents only).

So essentially we would need `HTML5_Link` module, which defines `link` element. We also need `LinkType` attribute definition  (with predefined list of allowed values, similar to `ARel`), and a `LinkRel` attribute definition as well (I assume valid `rel` values differ between `a` and `link`, so we need a separate definition class). Also, I believe we would need additional post-transform logic ensuring that the spec requirements are met (presence of `href` or `rel` values depending on `type`).

And of course we need a config toggle for link elements (`HTML.Link`).

Seems like a lot of work, so a PR is welcome.

**Comment by bytestream** [comment]
> long time no hear slightly_smiling_face

It is indeed, I hope you're doing good :)

> Seems like a lot of work, so a PR is welcome.

I only just saw your comment so naming conventions are a bit different, but I've sent a PR and will wait for your feedback.

**Comment by xemlock** [comment]
Resolved by #66.
