### ISSUE TITLE
Table without tbody

### ISSUE THREAD

**Issue by bytestream** [xemlock/htmlpurifier-html5#68]
In HTML5 it is permitted to omit the `<tbody>` from a `<table>` - https://html.spec.whatwg.org/multipage/tables.html#the-tbody-element

The result of processing the below HTML is an empty string.

```html
<table><thead><tr><th>foo</th></tr></thead></table>
```

Example valid HTML5 (https://validator.w3.org/nu/#textarea):
```html
<!DOCTYPE html>
<html lang="en">
<head><title>foo</title><meta http-equiv="content-type" content="text/html;charset=utf-8"></head>
<body><table><thead><tr><th>foo</th></tr></thead></table></body>
</html>
```

**Comment by xemlock** [comment]
Yes, unfortunately this is true. At the moment `<table>` uses the definition bundled with the original HTMLPurifier, which implements XHTML spec, not HTML5.

According to HTML5 even the following markup is valid:

```html
<table></table>
```

but at the moment is not accepted, so the empty table is dropped during purification.

**Comment by bytestream** [comment]
Let me know if you have a go at fixing it, otherwise I _may_ work on a PR. I think it's fairly low priority though...
