### ISSUE TITLE
(Table) Captions with Heading content results in a stripped table

### ISSUE THREAD

**Issue by codebymikey** [xemlock/htmlpurifier-html5#73]
In HTML5, `caption`s may contain any flow content excluding descendent `table` elements- https://html.spec.whatwg.org/multipage/tables.html#the-caption-element

Meaning: 
```html
<table>
  <caption><h3>Monthly savings</h3></caption>
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
</table>
```

is perfectly valid HTML, but it results in the entire table being stripped out instead:

```html
<h3>Monthly savings</h3>
  Month
    Savings
  January
    $100
  
```

Related issue: https://github.com/ezyang/htmlpurifier/issues/131

**Comment by codebymikey** [comment]
When this is resolved, are there any plans to create a new release for the table support added as part of #70?

It's at least better than losing all your captioned tables.

**Comment by xemlock** [comment]
Hi @codebymikey,
I plan to make a release (0.1.12) when the support for form input types (#59) is ready. Ideally I'd like to finish working on it by the end of the summer (around last week of September).

Is this timeline acceptable to you?

**Comment by codebymikey** [comment]
Yeah that's fine, a beta pre-release would be ideal, but if not I can just stick to dev for now until 0.1.12 is stable.
