### ISSUE TITLE
contenteditable attribute

### ISSUE THREAD

**Issue by bytestream** [xemlock/htmlpurifier-html5#77]
Would you accept a PR which adds contenteditable attribute support?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

**Comment by bytestream** [comment]
I sent a PR upstream https://github.com/ezyang/htmlpurifier/pull/332

**Comment by xemlock** [comment]
Gladly!
But as potentially unsafe, the attribute has to be enabled explicitly via a dedicated flag (not sure about the name though, `Attr.EnableContenteditable` perhaps?). I would see it implemented as an AttrDef, similarly to how ID is done.

**Comment by bytestream** [comment]
It got merged upstream so I'll close this :)
